### ISSUE TITLE
Long timeout

### ISSUE THREAD

**Issue by brancengregory** [Hegghammer/daiR#1]
When a Processor ID is entered incorrectly to environment variable, if you submit a request using `dai_sync` the request will hang, with no timeout

**Comment by Hegghammer** [comment]
Thanks for letting me know! Can I just clarify what you mean by "incorrectly" - do you mean a processor ID that is incorrectly formatted (e.g. with a space in the middle) or one that is correctly formatted but not associated with the user?

**Comment by brancengregory** [comment]
Sorry for the slow response. My comment regards your second statement: one that is correctly formatted but not associated with the user. Thanks

**Comment by Hegghammer** [comment]
Ok, I see. I'll see if I can put in a kill switch or something.

**Comment by brancengregory** [comment]
Thank you for all your work!

**Comment by Hegghammer** [comment]
I am unable to replicate the error. When I submit a `dai_sync()` request with a fictional `proc_id` ("1234567890123456") - whether supplied directly as a parameter or via an environmental variable - I get the following error message after about 5 seconds: "File submitted at <time>. HTTP status: 404 - unsuccessful.
Error: "Processor with id '1234567890123456' not found."

**Comment by brancengregory** [comment]
Hmm okay. It has been a while since I was experiencing it, and don't have time to reproduce on my end. If I run in to the issue again I will document what happens better. We can close this for now. Thanks so much
