### ISSUE TITLE
PDF is not recognized?

### ISSUE THREAD

**Issue by bhanberry** [Hegghammer/daiR#10]
**Describe the problem**
The pdf does not appear to be recognized. It works within the Form Parser analysis, but I would like to use an R workflow.

**Summarize the procedure**
> resp <- dai_sync("Gila River Forest Reserve, New Mexico 22.pdf", proc_id = formparser_id)
Error: Rgui.exe: CompressionNotSupported `JPEG' @ error/tiff.c/WriteTIFFImage/3398

** Your configuration**
 - OS: [Windows 10]
 - R version [R 4.4.0]

**Additional context and screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain your problem.

**Comment by Hegghammer** [comment]
Potentially related to [#9](https://github.com/Hegghammer/daiR/issues/9).

Try installing the development version.

If that does not work, let me know if the problem occurs with all PDFs or just this one.

**Comment by bhanberry** [comment]
Yes, that worked! But another issue.
> resp <- dai_sync("Gila River Forest Reserve, New Mexico 22.pdf", proc_id = formparser_id)
✖ File submitted at 2024-06-07 21:12:17. HTTP status: 400 - unsuccessful.
Error: "Request contains an invalid argument."

**Comment by Hegghammer** [comment]
That last issue is now fixed in v. 1.0.1.
