### ISSUE TITLE
vignette: mathematical splitting

### ISSUE THREAD

**Issue by whanley** [Hegghammer/daiR#3]
The vignette on mathematical splitting gives this function: `new_block_df <- split_block(df = block_df, block = 12, cut_point = 50)`

However, the dataframe argument does not require `df =` and gives an error. Update vignette to `new_block_df <- split_block(block_df, block = 12, cut_point = 50)`?

**Comment by Hegghammer** [comment]
Well spotted! I changed the parameter name at one point and forgot to adjust the vignette. Many thanks for the note
