### ISSUE TITLE
redraw blocks?

### ISSUE THREAD

**Issue by whanley** [Hegghammer/daiR#4]
Hi Thomas, it's me again. Obviously I'm enjoying daiR!

I'm working on multipage journals with complex layouts. I can reorder and split blocks. However I'm finding I'm getting a bit lost when I make a lot of changes. I wonder if you might be able to suggest a procedure that would redraw blocks based on my reordering and splits? That way, I could confirm that I have things in the right order.

I'm thinking that what's needed is to update my .json file using the new tokens and blocks, then pass that revised file through `draw_blocks`. But I can't see how. Any suggestions? 

If it's not too complex, this might be a useful addition to the vignette, as I'd assume that some others would have the same need. 

Thanks for your work! Will

**Comment by Hegghammer** [comment]
And I am thrilled to see daiR in use! 
This is a great suggestion. daiR needs a function that can draw blocks on an image based on a revised block data frame. It's definitely doable. Give me a few days

**Comment by Hegghammer** [comment]
I have added a new function called `redraw_blocks()`. You can try it out by downloading the development version: `devtools::install_github("hegghammer/daiR")`  Let me know if it does the job.

**Comment by whanley** [comment]
Finally getting back to this. `redraw_blocks()` works perfectly--thanks so much. I'm trying to figure out a good workflow for a research assistant, and I'll share it when I have it. Can't promise more questions won't arise! Thanks again.
