### ISSUE TITLE
HTTP status: 408 - unsuccessful.

### ISSUE THREAD

**Issue by tweedmann** [Hegghammer/daiR#5]
Hi Thomas, thank you for this amazing package. I was trying to replicate the User Guide example daiR::extracting_tables with the following code:

library(daiR)
dest_path <- file.path(tempdir(), "tobacco.pdf")
download.file("https://archive.org/download/tobacco_lpnn0000/lpnn0000.pdf", 
              destfile = dest_path,
              mode = "wb")

resp <- dai_sync_tab(dest_path)

However, the function dai_sync_tab always results in a error message:
File submitted at 2021-12-21 18:16:25. HTTP status: 408 - unsuccessful.

Did you encounter this before? Do you know what causes this problem?

Thanks in advance
Tobias

P.S: Fyi, I set up authentication following this guide (https://dair.info/articles/setting_up_google_storage.html) and everything seems to be working fine.

**Comment by tweedmann** [comment]
Just as additional information: the code line from above

`resp <- dai_sync_tab(dest_path)`

creates a large response object, however, when I try to turn the object into a dataframe with this code from the userguide

`tables <- tables_from_dai_response(resp)`

I again get an error message:

Error in tables_from_dai_response(resp) : 
  Object not a positive dai_sync response.

**Comment by Hegghammer** [comment]
Hi Tobias,

Thanks for your message. I haven't encountered this before I'm afraid, and the code runs fine on my end. 

The second error (the tables failing to parse) is likely a follow on from the initial processing error. I'm not quite sure what the source of that first error may be, though. HTTP 408 means "request timeout", which I suppose can arise for a variety of reasons. The documentation for Google Storage (https://cloud.google.com/storage/docs/json_api/v1/status-codes) links 408 to a "broken connection" and recommends retrying at gradually increasing time intervals until it works (https://cloud.google.com/storage/docs/retry-strategy#exponential-backoff). But it's odd that this should happen for a single file. Have you tried re-running the code recently?
