### ISSUE TITLE
[PROBLEM]: Error: rsession: Wrong JPEG library version: library is 90, caller expects 80. `JPEGLib' @ error/tiff.c/TIFFErrors/542

### ISSUE THREAD

**Issue by giladwenig** [Hegghammer/daiR#9]
I'm trying to send a PDF to Document AI for synchronous processing (using the dai_sync function), but I keep on receiving this error:

Error: rsession: Wrong JPEG library version: library is 90, caller expects 80. `JPEGLib' @ error/tiff.c/TIFFErrors/542

Any help here would be appreciated. Thanks. 

 - macOS 14 Sonoma
 - R version 4.3.0
 - RStudio 2023.06.0

**Comment by Hegghammer** [comment]
As it happens, I addressed this problem in a recent commit. Try installing the development version with `devtools::install_github("hegghammer/daiR")`.

**Comment by giladwenig** [comment]
That works — thanks!
